# Generated by Django 3.1.1 on 2020-09-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GivenPlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('latitute', models.FloatField()),
                ('longitute', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LatituteAndLongituteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitute', models.FloatField()),
                ('longitute', models.FloatField()),
                ('agents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentsmodel')),
            ],
        ),
    ]
